# Site settings
title: وبلاگ کوارتز
email: info@webquartz.com
description: > # this means to ignore newlines until "baseurl:"
  در این وبلاگ مطالب آموزشی در باره طراحی وب، برنامه نویسی وب به زبان PHP
  و همچنین مطالبی در خصوص لینوکس و سایر تکنولوژی های متن باز را خواهید یافت
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.webquartz.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  webquartz

# Build settings
markdown: kramdown
